# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-08 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 5, 8, 17, 33, 31, 806143), verbose_name='Опубликована'),
        ),
    ]
